### ISSUE TITLE
 cancellationSignal is missing

### ISSUE THREAD

**Issue by natiginfo** [pwittchen/RxBiometric#15]
In Readme file, it's mentioned that we can set cancellation signal using `cancellationSignal(cancellationSignal)`, however, it's missing from library.

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting that. You're right. It looks like I wanted to add it, defined it in docs, but forgot to implement it. Hopefully, I'll add it soon. I'm also open for PRs if anyone is in hurry :).

Regards,
Piotr

**Comment by pwittchen** [comment]
I see that cancellationSignal is not available as a parameter in any variant of `androidx.biometric.BiometricPrompt#authenticate(...)` method from `androidx` package to which library was migrated. It was possible to use it before migration to `androidx` and it's visible in docs for another package. Due to this fact, I'm not able to add it right now. It's not critical and it's possible to use library without it anyway. I just removed information about it from the docs in `README.md`.
